apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: overcookied
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::032073356456:role/overcookied-backend-pod-role"
  labels:
    app: overcookied-backend
